#!headstart

users:
  user1:
    name: Bob Loblaw
    authorized_keys:
      - key1
      - key2

disks:
  /dev/xda1:
    fs: ext4
    options: noatime
    mount: /var/lib/docker

files:
  /var/lib/kubelet/kubeconfig:
    source: https://gist.githubusercontent.com/deedubs/64ca227f953a93ef874caf60f5e170e4/raw/499e9d67a7403488811f52479fc192c833f7aae5/user-data.yml
    hash: 123asd123
    mode: 0600
    owner: root
    group: wheel
  /Users/deedubs/go/src/github.com/massiveco/headstart/file:
    contents: Hello World!!
    mode: 0600
scripts:
  - slack --channel=ops ${HOSTNAME} has arrived!